### ISSUE TITLE
前辈，第一次用taro，也是第一次用echarts，最近开始移动端项目，做图表展示，那个默认的200px高度怎么增加？

### ISSUE THREAD

**Issue by wjm0913** [cangku/easy-work#1]
我在图表配置了  grid .
<img width="697" alt="屏幕快照 2019-10-03 上午12 57 25" src="https://user-images.githubusercontent.com/45306520/66064868-d726ef00-e578-11e9-9597-7966e262e746.png">会变这个样子，用style设置，图表 直接不展示，没有宽度和高度！

**Comment by wjm0913** [comment]
<img width="697" alt="屏幕快照 2019-10-03 上午1 26 42" src="https://user-images.githubusercontent.com/45306520/66066862-f0ca3580-e57c-11e9-9423-87afb46c936e.png">好了，但是 我不知掉 这样改 会不会出问题，我直接吧配置文件里买呢的animationDurationUpdate修改了！！！！

**Comment by wjm0913** [comment]
已经 解决，看了一下封装index文件，style要的是一个字符串，我一直在style={{}}这样；为什么 不直接返回EcCanvas，求答案！谢谢，前辈的组建，很好用！

**Comment by cangku** [comment]
高度默认 200 是因为在 `h5` 下需要默认一个高度，然后小程序端就保持了一致性。没返回 EcCanvas 也是同理，h5 下没有 EcCanvas。
有其它好的使用建议也可以反馈哦，我做的时候基本也是按照开发中使用的习惯来考虑的。

**Comment by wjm0913** [comment]
三克油，明白了，我这边不考虑兼容h5.很棒。谢谢
