### ISSUE TITLE
你好，作者，将option放到函数中，修改state后，环形图会重复渲染2次，仪表图会重复渲染无数次，请问如何解决这个问题呢

### ISSUE THREAD

**Issue by Sam1141968878** [cangku/easy-work#10]
你好，作者，将option放到函数中，修改state后，环形图会重复渲染2次，仪表图会重复渲染无数次，请问如何解决这个问题呢
![image](https://user-images.githubusercontent.com/24800090/71616710-9def3100-2bf2-11ea-9bdd-f2d6b952161d.png)
![image](https://user-images.githubusercontent.com/24800090/71616719-a8a9c600-2bf2-11ea-9aa7-9357e1b386bb.png)

**Comment by Sam1141968878** [comment]
<Echart
                          option={ this.getOptionOne()}
                          style='height:100px;width:120px'
                          ec={{
                              lazyLoad:true
                          }}
                      >
                      </Echart>

**Comment by Sam1141968878** [comment]
getOptionOne(value){
      return {
          tooltip : {
              formatter: "{a} <br/>{b} : {c}%"
          },
          toolbox: {
              feature: {
                  restore: {},
                  saveAsImage: {}
              }
          },
          series: [
              {
                  name: '业务指标',
                  type: 'gauge',
                  detail: {formatter:'{value}%'},
                  data: [{value: value, name: '完成率'}]
              }
          ]
      }
  }

**Comment by cangku** [comment]
`getOptionOne(value)` 与 `{this.getOptionOne()}` 这里是简化代码的问题？state 修改以后会触发 render ，option 的修改 diff 在 taro 中的判断之前测试过程中有些问题，就会触发多次渲染。option 如果不是定时更新的数据可以静态化

**Comment by Sam1141968878** [comment]
作者你好，如果我把数据放到变量里而不是函数里，它就会只监听我刚开始定义的状态的量，我是组件将要加载的时候改变一次状态的值，但是并没有让我第一次被修改的值被监听触发视图更新 谢谢作者了，元旦快乐------------------ 原始邮件 ------------------
发件人: "unofficial"<notifications@github.com>
发送时间: 2019年12月31日(星期二) 晚上6:09
收件人: "cangku/easy-work"<easy-work@noreply.github.com>;
抄送: "李观汉"<1141968878@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [cangku/easy-work] 你好，作者，将option放到函数中，修改state后，环形图会重复渲染2次，仪表图会重复渲染无数次，请问如何解决这个问题呢 (#10)



getOptionOne(value) 与 {this.getOptionOne()} 这里是简化代码的问题？state 修改以后会触发 render ，option 的修改 diff 在 taro 中的判断之前测试过程中有些问题，就会触发多次渲染。option 如果不是定时更新的数据可以静态化
 
&mdash;

**Comment by cangku** [comment]
@liguanhan  元旦快乐。如果你还是有问题明天我最小化一个demo看下。

**Comment by Sam1141968878** [comment]
谢谢作者，我这里确实有点问题，特别是仪表图会重复渲染 作者我这里还有一个新的问题，就是安卓的环行图会把内坏的颜色变成背景，ios没有这个问题 ，既我想环行图中间没有颜色，但是安卓上它是内坏的颜色------------------ 原始邮件 ------------------
发件人: "unofficial"<notifications@github.com>
发送时间: 2020年1月1日(星期三) 晚上6:58
收件人: "cangku/easy-work"<easy-work@noreply.github.com>;
抄送: "李观汉"<1141968878@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [cangku/easy-work] 你好，作者，将option放到函数中，修改state后，环形图会重复渲染2次，仪表图会重复渲染无数次，请问如何解决这个问题呢 (#10)



@liguanhan  元旦快乐。如果你还是有问题明天我最小化一个demo看下。
 
&mdash;

**Comment by Sam1141968878** [comment]
@cangku 谢谢作者，麻烦了

**Comment by cangku** [comment]
@liguanhan  不好意思，有些忙没来得及帮忙查看问题。先查看一下你本地的版本是什么？option 的变更会触发重新渲染，在判断对象是否相等时处理的比较简单，这里重新更新了一个版本，你再更新版本重试一下呢。 仪表盘： https://developers.weixin.qq.com/s/L7un57mS7zel

**Comment by cangku** [comment]
有问题继续反馈
