### ISSUE TITLE
源代码疑问

### ISSUE THREAD

**Issue by LOUSANPANG** [cangku/easy-work#2]
**很棒的代码转化🌹， 但对代码中有几个疑问，需要您的解答❤。**

**疑问描述**
1. 代码中的 `this.data` ❤
![image](https://user-images.githubusercontent.com/36870764/66635515-f7724000-ec41-11e9-841f-814ed4ab1e81.png)
2. 关于函数 `canvasToTempFilePath` 在这里的作用 ❤
![image](https://user-images.githubusercontent.com/36870764/66635748-71a2c480-ec42-11e9-8d45-7675ef6c3bdf.png)

**系统信息**
 - Taro 版本 [v.1.3.17]
 - Node.js 版本 [v10.16.3]
 - 报错平台 [weapp]

**Comment by cangku** [comment]
首先感谢你的 issue，这里的问题多数是一些不影响使用的冗余代码，源码的参考来源于 https://github.com/ecomfe/echarts-for-weixin
- 第一个问题
这里其实是几种使用形式，因为在 `index.js` 中调用了组件 `EcCanvas` 方法 `init` 初始化的时候传入了 `function` ，默认情况下走的就是 `if`，至于 `else-if` 中的 `this.data` 这里需要修改为 `this.props` ，使用 `EcCanvas` 的时候传入 `prop` 就可以了。（这里是拷贝过来代码多余的没有优化）

- 第二个问题
这里是有保存图表为图片需求的可以使用这个方法，这里也还没有处理，this.data 同上，还有就是没有处理好回调数据以及this指向问题

再次感谢反馈，后面我找时间优化重新提交一个版本

**Comment by LOUSANPANG** [comment]
> 首先感谢你的问题，这里的问题多个是一些不影响使用的冗余代码，原始代码的参考偏移https://github.com/ecomfe/echarts-for-weixin
> 
> * 第一个问题
>   这里其实是几种使用形式，因为在`index.js`中调用了组件`EcCanvas`方法`init`初始化的时候初始化了`function`，有时情况下走的就是`if`，到于`else-if`中的`this.data`这里需要修改为`this.props`，使用`EcCanvas`的时候放置`prop`可以可以了。 （这里是拷贝过来代码多余的没有优化）
> * 第二个问题
>   这里是有保存图表为图片需求的可以使用这个方法，这里也还没有处理，this.data同上，还有就是没有处理好数据以及此指向问题
> 
> 再次感谢反馈，后面我找时间优化重新提交一个版本

------------------------
自己在转化的过程中，受到 `echarts12` 的启发才得以运行。

谢谢⭐

**Comment by cangku** [comment]
相互学习
