### ISSUE TITLE
   tooltip: {         trigger: 'axis'     },不能使用啊，兄弟

### ISSUE THREAD

**Issue by QianSu** [cangku/easy-work#5]

**Comment by cangku** [comment]
注意两个地方
- 目前只能使用包自带的 `echarts.js`
- 需要开启 `touch`  事件，配置一下 `disableTouch: false`，配置方法 `<Echart ec={ { disableTouch: false } } option={ ... } />`

**Comment by QianSu** [comment]
谢谢 已经不错了

**Comment by cangku** [comment]
问题解决了就好
