### ISSUE TITLE
无法点击图表，配置了提示框与标题.

### ISSUE THREAD

**Issue by is-nan** [cangku/easy-work#6]
无法点击图表，配置了提示框与标题，option配置肯定是没问题的。

**Comment by cangku** [comment]
注意两个地方

- 目前只能使用包自带的 echarts.js
- 需要开启 touch 事件，配置一下 disableTouch: false，配置方法 <Echart ec={ { disableTouch: false } } option={ ... } />

**Comment by is-nan** [comment]
> 注意两个地方
> 
> * 目前只能使用包自带的 echarts.js
> * 需要开启 touch 事件，配置一下 disableTouch: false，配置方法 <Echart ec={ { disableTouch: false } } option={ ... } />

感谢你的回复，问题解决了.
